---
- hosts: all
  become: yes
  tasks:
    - name: Mars client
      ansible.builtin.include_role:
        name: ewc-ansible-role-mars-client

    - name: ai-models
      ansible.builtin.include_role:
        name: ewc-ansible-role-ai-models